services:
  extractor_service:
    build:
      context: ./extractor_service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - cache_volume:/root/.cache
      - "B:/frames_evaluators/input_directory:/app/input_directory"
      - "B:/frames_evaluators/output_directory:/app/output_directory"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    working_dir: /app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100" ]

volumes:
  cache_volume: