@echo off
echo Starting PerfectFrameAI (GPU mode)...
docker-compose --profile gpu up --build -d
echo Waiting for service to start...
timeout /t 60 /nobreak >nul
echo Calling best_frames_extractor...
curl -X POST http://localhost:8100/v2/extractors/best_frames_extractor
echo.
echo Results will appear in output_directory/
echo Press any key to stop the service...
pause >nul
docker-compose --profile gpu down
