sonar.projectKey=BKDDFS_PerfectFrameAI
sonar.organization=bkddfs
sonar.projectName=PerfectFrameAI

sonar.sources=perfectframe
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.13

sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=tests/**
