sonar.organization=bkddfs
sonar.projectKey=BKDDFS_PerfectFrameAI
sonar.projectName=PerfectFrameAI

sonar.sources=perfectframe
sonar.tests=tests

sonar.exclusions=**/tests/**,**/__pycache__/**
sonar.cpd.exclusions=**/tests/**

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
